### ISSUE TITLE
Dependency on headless system's 

### ISSUE THREAD

**Issue by Saentist** [jbonet/tvhstats#8]
Ubuntu 20.04 LTS Server

```
docker-compose build
[+] Building 0.9s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                          0.1s
 => => transferring dockerfile: 824B                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                             0.1s
 => => transferring context: 2B                                                                                                                               0.0s
 => ERROR [internal] load metadata for docker.io/library/elixir:1.14-alpine                                                                                   0.7s
------
 > [internal] load metadata for docker.io/library/elixir:1.14-alpine:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: `GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files`

```

`gnome-keyring` needed but pc is headless no GUI
after installing 

```
The following NEW packages will be installed:
  adwaita-icon-theme at-spi2-core dconf-gsettings-backend dconf-service gcr glib-networking glib-networking-common glib-networking-services gnome-keyring
  gnome-keyring-pkcs11 gsettings-desktop-schemas gtk-update-icon-cache hicolor-icon-theme humanity-icon-theme libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data
  libatspi2.0-0 libavahi-client3 libavahi-common-data libavahi-common3 libcairo-gobject2 libcolord2 libcups2 libdconf1 libepoxy0 libgck-1-0 libgcr-base-3-1
  libgcr-ui-3-1 libgtk-3-0 libgtk-3-bin libgtk-3-common libjson-glib-1.0-0 libjson-glib-1.0-common liblcms2-2 libpam-gnome-keyring libproxy1v5 librest-0.7-0
  libsoup-gnome2.4-1 libsoup2.4-1 libxcomposite1 libxtst6 p11-kit p11-kit-modules pinentry-gnome3 ubuntu-mono
0 upgraded, 46 newly installed, 0 to remove and 0 not upgraded.
Need to get 10.6 MB of archives.
After this operation, 57.3 MB of additional disk space will be used.
```

```
docker-compose build
[+] Building 25.7s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                          0.0s
 => => transferring dockerfile: 32B                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                               0.0s
 => ERROR [internal] load metadata for docker.io/library/elixir:1.14-alpine                                                                                  25.7s
------
 > [internal] load metadata for docker.io/library/elixir:1.14-alpine:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: `Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached`
```

Any ideas are welcome.

**Comment by Saentist** [comment]
cr.jbonet.xyz/jbonet/tvhstats
error 404 not existing

**Comment by jbonet-df** [comment]
> cr.jbonet.xyz/jbonet/tvhstats
> error 404 not existing 

Check now it was down

**Comment by jbonet** [comment]
> cr.jbonet.xyz/jbonet/tvhstats error 404 not existing

Check now, it was down.

You should not build the image for using it, the prebuilt works fine, and it's alpine based

**Comment by Saentist** [comment]
prebuild image is not happy solution

``` erlang
sudo docker run -p 4080:4080 -e DATABASE_URL=ecto://db_user:db_password@db_host/db -e SECRET_KEY_BASE=secret_string_REPLACE_ME cr.jbonet.xyz/jbonet/tvhstats
ERROR! Config provider Config.Reader failed with:
** (RuntimeError) environment variable PHX_ALLOWED_HOSTS is missing.
For example: localhost:8080

    /app/releases/0.0.1/runtime.exs:70: (file)
    (elixir 1.14.1) src/elixir.erl:298: anonymous fn/4 in :elixir.eval_external_handler/1
    (stdlib 4.1.1) erl_eval.erl:748: :erl_eval.do_apply/7
    (stdlib 4.1.1) erl_eval.erl:492: :erl_eval.expr/6
    (stdlib 4.1.1) erl_eval.erl:136: :erl_eval.exprs/6
    (elixir 1.14.1) src/elixir.erl:288: :elixir.eval_forms/3
    (elixir 1.14.1) lib/module/parallel_checker.ex:107: Module.ParallelChecker.verify/1
    (elixir 1.14.1) lib/code.ex:422: Code.validated_eval_string/3

{
    "init terminating in do_boot", {
         # {
            '__exception__' => true,
            '__struct__' => 'Elixir.RuntimeError',
            message =>  << 101,
            110,
            118,
            105,
            114,
            111,
            110,
            109,
            101,
            110,
            116,
            32,
            118,
            97,
            114,
            105,
            97,
            98,
            108,
            101,
            32,
            80,
            72,
            88,
            95,
            65,
            76,
            76,
            79,
            87,
            69,
            68,
            95,
            72,
            79,
            83,
            84,
            83,
            32,
            105,
            115,
            32,
            109,
            105,
            115,
            115,
            105,
            110,
            103,
            46,
            13,
            10,
            70,
            111,
            114,
            32,
            101,
            120,
            97,
            109,
            112,
            108,
            101,
            58,
            32,
            108,
            111,
            99,
            97,
            108,
            104,
            111,
            115,
            116,
            58,
            56,
            48,
            56,
            48,
            13,
            10 >>
        },
        [{
                elixir_eval,
                '__FILE__',
                1,
                [{
                        file,
                        "/app/releases/0.0.1/runtime.exs"
                    }, {
                        line,
                        70
                    }
                ]
            }, {
                elixir,
                '-eval_external_handler/1-fun-2-',
                4,
                [{
                        file,
                        "src/elixir.erl"
                    }, {
                        line,
                        298
                    }, {
                        error_info,
                         # {
                            module => 'Elixir.Exception'
                        }
                    }
                ]
            }, {
                erl_eval,
                do_apply,
                7,
                [{
                        file,
                        "erl_eval.erl"
                    }, {
                        line,
                        748
                    }
                ]
            }, {
                erl_eval,
                expr,
                6,
                [{
                        file,
                        "erl_eval.erl"
                    }, {
                        line,
                        492
                    }
                ]
            }, {
                erl_eval,
                exprs,
                6,
                [{
                        file,
                        "erl_eval.erl"
                    }, {
                        line,
                        136
                    }
                ]
            }, {
                elixir,
                eval_forms,
                3,
                [{
                        file,
                        "src/elixir.erl"
                    }, {
                        line,
                        288
                    }
                ]
            }, {
                'Elixir.Module.ParallelChecker',
                verify,
                1,
                [{
                        file,
                        "lib/module/parallel_checker.ex"
                    }, {
                        line,
                        107
                    }
                ]
            }, {
                'Elixir.Code',
                validated_eval_string,
                3,
                [{
                        file,
                        "lib/code.ex"
                    }, {
                        line,
                        422
                    }
                ]
            }
        ]
    }
}
init terminating in do_boot({ ,
    [{
            elixir_eval,
            __FILE__,
            1,
            [{
                    _
                }, {
                    _
                }
            ]
        }, {
            elixir,
            -eval_external_handler / 1 - fun - 2 - ,
            4,
            [{
                    _
                }, {
                    _
                }, {
                    _
                }
            ]
        }, {
            erl_eval,
            do_apply,
            7,
            [{
                    _
                }, {
                    _
                }
            ]
        }, {
            erl_eval,
            expr,
            6,
            [{
                    _
                }, {
                    _
                }
            ]
        }, {
            erl_eval,
            exprs,
            6,
            [{
                    _
                }, {
                    _
                }
            ]
        }, {
            elixir,
            eval_forms,
            3,
            [{
                    _
                }, {
                    _
                }
            ]
        }, {
            Elixir.Module.ParallelChecker,
            verify,
            1,
            [{
                    _
                }, {
                    _
                }
            ]
        }, {
            Elixir.Code,
            validated_eval_string,
            3,
            [{
                    _
                }, {
                    _
                }
            ]
        }
    ]
})

Crash dump is being written to: erl_crash.dump...done
```

**Comment by jbonet** [comment]
It looks like youre missing some env variables, take a look at the readme for all that are required, such as phx_allowed_hosts

**Comment by Saentist** [comment]
that's why prefer manual run witch again fail

```
sudo docker-compose up
[+] Running 0/1
 ⠸ tvhstats Pulling                                                                                                               25.3s
[+] Building 25.8s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                               0.0s
 => => transferring dockerfile: 32B                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                  0.0s
 => => transferring context: 2B                                                                                                    0.0s
 => ERROR [internal] load metadata for docker.io/library/elixir:1.14-alpine                                                       25.6s
------
 > [internal] load metadata for docker.io/library/elixir:1.14-alpine:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: `Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached`

```
